.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. firstcoin_qt test_firstcoin_qt
clean: FORCE
	$(MAKE) -C .. firstcoin_qt_clean test_firstcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_firstcoin_qt_check
firstcoin-qt firstcoin-qt.exe: FORCE
	 $(MAKE) -C .. firstcoin_qt
