#ifndef FIRSTCOIN_CHAINPARAMSSEEDS_H
#define FIRSTCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the firstcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {
        {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0x68, 0x83, 0x0e, 0xf5}, 50033},
    {
        {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0x90, 0x4c, 0x67, 0x74}, 50033}
};

static SeedSpec6 pnSeed6_test[] = {
    {

    }
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
